name: Install and Test Check

on:
  pull_request:
    branches:
      - main

jobs:
  install_and_test:
    name: npm Install and Test Worklflow
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        options: >-
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"

      - name: Set environment variables
        env:
          DB_CONNECTION_URL: ${{ secrets.DB_CONNECTION_URL }}
          SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
          SERVER_PORT_NUMBER: ${{ secrets.SERVER_PORT_NUMBER }}
        run: |
          echo "Environment variables set from GitHub Secrets"

      - name: Setup DB
        run: |
          sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USERNAME }} WITH PASSWORD ${{ secrets.DB_PASSWORD }};"
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"
          sudo -u postgres psql -c "GRANT ALL ON DATABASE ${{ secrets.DB_NAME }} to ${{ secrets.DB_USERNAME }};"
          sudo -u postgres psql -c "ALTER DATABASE ${{ secrets.DB_NAME }} OWNER TO ${{ secrets.DB_USERNAME }};"

      - name: Install Dependencies
        run: npm install

      - name: Test Cases
        run: npm test

      - name: Build App
        run: npm build
