name: Packer Build AMI

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Packer Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          packer-version: 1.11.2

      - name: Install AWS-cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.RUNNER_AWS_KEY }}"
          aws-secret-access-key: "${{ secrets.RUNNER_AWS_SECRET }}"
          aws-region: "${{ secrets.RUNNER_AWS_REGION }}"

      # - name: Create Env file
      #   id: env
      #   run: touch .env && cat

      # - name: Put DB_CONNECTION_URL
      #   id: env-add1
      #   run: echo DB_CONNECTION_URL="${{ secrets.DB_CONNECTION_URL }}" >> .env

      # - name: Put SERVER_HOSTNAME
      #   id: env-add2
      #   run: echo SERVER_HOSTNAME=${{ secrets.SERVER_HOSTNAME }} >> .env

      # - name: Put SERVER_PORT_NUMBER
      #   id: env-add3
      #   run: echo SERVER_PORT_NUMBER=${{ secrets.SERVER_PORT_NUMBER }} >> .env

      - name: Install zip
        uses: montudor/action-zip@v1.0.0
        id: zip

      - name: Zip required files into webapp.zip
        id: zipppp
        run: zip -r webapp.zip src tsconfig.json package.json bable.config.js nodemon.json .env

      - name: Initialize Packer
        id: init
        run: packer init .

      - name: Format Check
        id: fmt
        run: packer fmt .

      - name: Packer Validate
        id: validate
        run: packer validate .

      # - name: Packer Build
      #   id: build
      #   run: packer build -var DB_CONNECTION_URL=${{ secrets.DB_CONNECTION_URL }} -var SERVER_HOSTNAME=${{ secrets.SERVER_HOSTNAME }} -var SERVER_PORT_NUMBER=${{ secrets.SERVER_PORT_NUMBER }} -var DB_NAME=${{ secrets.DB_NAME }} -var DB_USERNAME=${{ secrets.DB_USERNAME }} -var DB_PASSWORD=${{ secrets.DB_PASSWORD }} -var RUNNER_AWS_SECRET=${{ secrets.RUNNER_AWS_SECRET }} -var RUNNER_AWS_KEY=${{ secrets.RUNNER_AWS_KEY }} aws.pkr.hcl

      # - name: Print AMI ID
      #   id: print-id
      #   run: echo "AMI_ID=$(jq -r '.builds[0].artifact_id | split(":")[1]' ./manifest.json)" >> $GITHUB_ENV

      - name: Get Launch Templates
        id: get-launch-template
        run: echo "launch_template_id=$(aws ec2 describe-launch-templates | jq ".LaunchTemplates[0].LaunchTemplateId" | tr -d '"')" >> $GITHUB_ENV

      - name: Export ID to env and print to check
        id: export-ids
        run: |
          echo $AMI_ID
          echo $launch_template_id
          echo "$launch_template_id"
          echo $launch_template

      # - name: Create new Launch Template
      #   id: version-launch-template
      #   run: aws ec2 create-launch-template-version --launch-template-id $launch_template_id  --source-version 1  --launch-template-data "{\"ImageId\":\"$AMI_ID\"}"

      - name: Get ASG Name and Refresh
        id: get-asg
        run: |
          echo "ASG_NAME=$(aws autoscaling describe-auto-scaling-groups  | jq '.AutoScalingGroups[0].AutoScalingGroupName')" >> $GITHUB_ENV
          echo $ASG_NAME
          # REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME --query "InstanceRefreshId" --output text)
          # echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV

      - name: Wait for Instance Refresh Completion
        id: Waiting-for-refresh
        run: |
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name $ASG_NAME \
              --query "InstanceRefreshes[?InstanceRefreshId=='$REFRESH_ID'].Status" \
              --output text)

            echo "Current status: $STATUS"

            if [ "$STATUS" == "Successful" ]; then
              echo "Instance refresh completed successfully."
              break
            elif [ "$STATUS" == "Failed" ]; then
              echo "Instance refresh failed." >&2
              exit 1
            else
              echo "Waiting for instance refresh to complete..."
              sleep 30
            fi
          done
